# Site settings
title: Jommel's Development Journal
email: amorjk1@student.op.ac.nz
description: > # this means to ignore newlines until "baseurl:"
  Jommel's Portfolio
baseurl: "https://softenop.github.io/individual-portfolio-19-2-amorjk1/" # the subpath of your site, e.g. /blog/
url: "http://username.github.io" # the base hostname & protocol for your site
github_username: amorjk1

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
